### ISSUE TITLE
Custom model & dataset

### ISSUE THREAD

**Issue by larrywal-express** [lp6m/yolov5s_android#8]
Thanks for your good work. I have a customized model at two detection scale trained with four class.. How do I modify the code to fit the application? Moreso, how to set up --tfds_root for quantize.py?

**Comment by lp6m** [comment]
Q1: Does `two detection scale` means that scale of width and height is different?  

If so, you will need to modify the resize part of the input image and the scale calculation of the output bounding box image.  
The number of classes is also different, so the postprocess part also needs to be modified.

https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/cpp/postprocess.cpp#L18

Q2: `tfds_root` in quantize.py
In general, tensorflow quantization process needs sample input data.  
Instead of preparing a sample image in tfds format, you can modify `representative_dataset_gen` to return a custom training data image.   
https://github.com/lp6m/yolov5s_android/blob/master/convert_model/quantize.py#L16-L25

**Comment by lp6m** [comment]
There are no plans to support models with different height and width sizes in this repository, but the forked project seems to be making an attempt to do so. (I have not tested this.)
https://github.com/rjean/yolov5s_android/commit/a0eab903353169bf2a41d64bcdec0dc1b6ea02fc

**Comment by larrywal-express** [comment]
@Ip6m I mean two detection scale for anchors. I have just 6 anchors instead of the 9 anchors.

**Comment by lp6m** [comment]
If the number of anchors is different from original model, you need to modify `postprocess.cpp` in this repository.  

https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/cpp/postprocess.cpp

As described also in `app/README.md`, The algorithm of `postprocess.cpp` is equivalent to `Detect` layer of original yolov5 repositor. However, some variables are embedded as constants. It is possible to deal with this by making some modifications.
https://github.com/ultralytics/yolov5/blob/3e7c59ad3bf5414d4b2a26e018f397e27a51c6f1/models/yolo.py#L48-L68

**Comment by apanand14** [comment]
Hello @lp6m @larrywal-express ,

I have trained yolov5s on custom dataset (classes 2) and converted model to tflite-16fp. I also verified inference using detect.py and loading tflite model. it works fine locally. But when i use that model in your android app then, it doesn't give any error but also it doesn't draw any bounding box or do any detection. Can you please let me know what exactly I'm doing wrong in running custom tflite model in your app?? Your help will be appreciated.

Thank you in advance!!

**Comment by lp6m** [comment]
@apanand14 Check the output of `tfliteInterPreter` and `postprocess()`.  
If the number of classes is different, some parts of the code must be modified.  

https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/cpp/postprocess.cpp#L18
https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/java/com/example/tflite_yolov5_test/TfliteRunner.java#L178-L184
https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/java/com/example/tflite_yolov5_test/TfliteRunner.java#L191

**Comment by lp6m** [comment]
I write the tutorial for custom model & dataset. please check.  
https://github.com/lp6m/yolov5s_android/issues/14
